package com.cybage.controller;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.cybage.model.User;
import com.cybage.service.IUserService;
import com.cybage.service.UserServiceImpl;

import utility.JDBCUtility;

/**
 * Servlet implementation class LoginController
 */
@WebServlet(urlPatterns = { "/login", /* "/auth" */}, loadOnStartup = 1)
public class LoginController extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
	private IUserService userService = new UserServiceImpl();

	/**
	 * @see Servlet#init()
	 */
	// Can't add SqlException in the throws clause : since overrding form of the
	// method DOES NOT allow any NEW CHECKED excs.
	public void init() throws ServletException {
		// dao instance
		try {
			JDBCUtility.getConncetion();
			UserServiceImpl userService = new UserServiceImpl();

		} catch (Exception e) {
			// centralized exc handling in servlets
			// javax.ser }

		}
	}

	/**
	 * @see Servlet#destroy()
	 */
	public void destroy() {
		// dao's cleanup
		try {
			JDBCUtility.getConncetion();
			UserServiceImpl userService = new UserServiceImpl();

		} catch (Exception e) {
			// System.out.println("err in destroy of "+getClass()+" err "+e);
			throw new RuntimeException("err in destroy of " + getClass(), e);
		}
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// set resp cont type
		response.setContentType("text/html");
		// pw
		try (PrintWriter pw = response.getWriter()) {
			// read request data (req parameters) sent ffrom clnt ---> server
			// API of javax.servlet.ServletRequest : public String getParameter(String name)
			String email = request.getParameter("em");
			String password = request.getParameter("pass");
			System.out.println(email+" "+password);
			// Servlet invokes DAO's for authentication
			User user = userService.authenticateUser(email, password);
			System.out.println(user);
			// chk the outcome
			if (user == null) { // send retry link with err mesg
//				pw.print("<h5> Invalid Login Please <a href='validate.jsp'>Retry</a></h5>");
				System.out.println("in errorrr...");
				response.sendRedirect("loginError.jsp");
			}
			else {
				// pw.print("<h5> Login Successful : mesg from LoginServlet </h5>");
				// in case of successful login , request WC to get HttpSession object.
				// API of HttpServletRequest : HttpSession getSession()
				HttpServlet session = (HttpServlet) request.getSession();

				System.out.println("session id " + session.getClass());
				System.out.println("session's imple class " + session.getClass());// catatlina jar
				// WC creates EMPTY session obj in WC's heap n creates a cookie
				// name : JSESSIONID value : string generated by WC / clnt eg : dgadf65765dhf
				/*
				 * 2 : How to save data in HttpSession?(scope=entire session) API of
				 * HttpSession i/f public void setAttribute(String attrName,Object attrVal)
				 * 
				 */

				// session.setAttribute("user_details", user);
				// add dao instances under session scope
//				session.setAttribute("user_dao", userDao);
//				session.setAttribute("topic_dao", topicDao);
//				session.setAttribute("tut_dao", tutDao);

				// role based authorization
				if (user.getRole().equals("ADMIN")) {
					// How to redirect the clnt from one servelt to another ?
					// Method of javax.servlet.http.HttpServletResponse : public void
					// sendRedirect(String location) throws IOExc
					System.out.println("in admin...");
					response.sendRedirect("admin.jsp");
				}
				else if (user.getRole().equals("CUSTOMER")) {
					response.sendRedirect("customer.jsp");
					System.out.println("in customer...");
				} else
					response.sendRedirect("loginError.jsp");// WC temp redirect resp : SC 302 | Location : topics,
															// set-cookie :
				// cookie : JSESSIONID : gfdjg687466 | Body : EMPTY
				// clnt browser chks for privacy settings --cookies enabled --age =-1 => cookie
				// will be stored in the browser's cache.
				// clnt browser sends NEXT redirect request : method =GET , URL :
				// http://host:port/day5_cms/topics
				// req header : cookie : JSESSIONID : gfdjg687466
			}

		} catch (Exception e) {
			throw new ServletException("err in do-post of " + getClass(), e);
		}
	}

}